title: Mayank Solanki
logo: /assets/img/head-circle-photograph.png
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal

# Otherhemes

# Architect
# Cayman
# Dinky
# Hacker
# Leap day
# Merlot
# Midnight
# Minima
# Minimal
# Modernist
# Slate
# Tactile
# Time machine
